### ISSUE TITLE
Unknown Mol2Block "@<TRIPOS>UNITY_ATOM_ATTR"

### ISSUE THREAD

**Issue by blakeo2** [SEDenmarkLab/molli#62]
The following multimol2 file has an unknown mol2 block. Also worth noting this file came from the following website:

https://chemoinfo.ipmc.cnrs.fr/MOLDB/index.php#ref3

[e-Drug3D_2083.txt](https://github.com/SEDenmarkLab/molli/files/12563503/e-Drug3D_2083.txt)

**Comment by esalx** [comment]
Added support for UNITY_ATOM_ATTR and UNITY_BOND_ATTR. Those are now parsed into atom and bond attributes. The only special treatment is for atom charge, which updates the corresponding formal_charge field. This will appear in the upcoming bugfix pull request.
